version: "3"

services:
    app:
        build:
            context: .
        ports:
            - 8000:8000
        volumes:
            - ./app:/app # This way we get code updates immediately w/o having to rebuild the image.
        # This command runs the dev server.
        command: >
            sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
        environment: 
            - DB_HOST=db
            - DB_NAME=app
            - DB_USER=postgres
            - DB_PASSWORD=supersecretpass
        depends_on: 
            - db

    db:
        image: postgres:10-alpine
        environment:
            - POSTGRES_DB=app
            - POSTGRES_USER=postgres
            # In production, you don't want to explicitly write out your password here.
            # What you would do is have your build server/service (eg Jenkins, TravisCI) add an
            # encrypted env variable that overwrites the var below at build time.
            - POSTGRES_PASSWORD=supersecretpass

